
var fieldNames = {
    "author" : "Autor",
    "title" : "Titel",
    "publisher" : "Verlag",
    "month" : "Monat",
    "year" : "Jahr",
    "editor" : "Herausgeber",
    "volume" : "Band",
    "number" : "Ausgabe",
    "series" : "Serie",
    "address" : "Adresse",
    "edition" : "Edition",
    "pages" : "Seiten",
    "chapter" : "Kapitel",
    "booktitle" : "Buchtitel",
    "journal" : "Zeitschrift",
    "note" : "Notizen",
    "tags" : "Schlagwörter",
};

// the field 'tags' is automatically appended!

var types = {
    "article" : {
            "name" : "Artikel",
            "fields" : [ "author",
                "title",
                "journal",
                "month",
                "year",
                "volume",
                "number",
                "pages",
                "note" ],
        },
    "book" : {
            "name" : "Buch",
            "fields" : [
                "author",
                "title",
                "publisher",
                "month",
                "year",
                "editor",
                "volume",
                "number",
                "series",
                "address",
                "edition",
                "note",
            ],
        },
        "booklet" : {
            "name" : "Booklet",
            "fields" : [
                "author",
                "title",
                "howpublished",
                "month",
                "year",
                "address",
                "note",
            ],
        },
        "inbook" : {
            "name" : "Buchkapitel",
            "fields" : [
                "author",
                "title",
                "publisher",
                "editor",
                "month",
                "year",
                "chapter",
                "volume",
                "number",
                "series",
                "edition",
                "pages",
                "address",
                "note",
            ],
        },
        "incollection" : {
            "name" : "Beitrag im Sammelband",
            "fields" : [
                "author",
                "title",
                "booktitle",
                "publisher",
                "editor",
                "month",
                "year",
                "chapter",
                "volume",
                "number",
                "series",
                "edition",
                "pages",
                "address",
                "note",
            ],
        }
}
