
var fieldNames = {
    "authors" : "Autor",
    "title" : "Titel",
    "publisher" : "Verlag",
    "month" : "Monat",
    "year" : "Jahr",
    "editor" : "Herausgeber",
    "volume" : "Band",
    "number" : "Ausgabe",
    "series" : "Serie",
    "address" : "Adresse",
    "edition" : "Edition",
    "pages" : "Seiten",
    "chapter" : "Kapitel",
    "booktitle" : "Buchtitel",
    "journal" : "Zeitschrift",
    "notes" : "Notizen",
    "tags" : "Schlagwörter",
};


var types = {
    "article" : {
            "name" : "Artikel",
            "divSelector" : "articleDetails",
            "formSelector" : "articleDetailsForm",
            "fields" : [ "authors",
                "title",
                "journal",
                "month",
                "year",
                "volume",
                "number",
                "pages",
                "tags",
                "notes" ],
            "template" : { "type" : "article" }
        },
    "book" : {
            "name" : "Buch",
            "divSelector" : "bookDetails",
            "formSelector" : "bookDetailsForm",
            "fields" : [
                "authors",
                "title",
                "publisher",
                "month",
                "year",
                "editor",
                "volume",
                "number",
                "series",
                "address",
                "edition",
                "tags",
                "notes",
            ],
            "template" : { "type" : "book" }
        },
        "booklet" : {
            "name" : "Booklet",
            "divSelector" : "bookletDetails",
            "formSelector" : "bookletDetailsForm",
            "fields" : [
                "authors",
                "title",
                "howpublished",
                "month",
                "year",
                "address",
                "tags",
                "notes",
            ],
            "template" : { "type" : "booklet" }
        },
        "inbook" : {
            "name" : "Buchkapitel",
            "divSelector" : "inbookDetails",
            "formSelector" : "inbookDetailsForm",
            "fields" : [
                "authors",
                "title",
                "publisher",
                "editor",
                "month",
                "year",
                "chapter",
                "volume",
                "number",
                "series",
                "edition",
                "pages",
                "address",
                "tags",
                "notes",
            ],
            "template" : { "type" : "inbook" }
        },
        "incollection" : {
            "name" : "Beitrag im Sammelband",
            "divSelector" : "incollectionDetails",
            "formSelector" : "incollectionDetailsForm",
            "fields" : [
                "authors",
                "title",
                "booktitle",
                "publisher",
                "editor",
                "month",
                "year",
                "chapter",
                "volume",
                "number",
                "series",
                "edition",
                "pages",
                "address",
                "tags",
                "notes",
            ],
            "template" : { "type" : "inbook" }
        }
}
